import type { MigrationToolOption } from '../types';

export const MIGRATION_TOOLS: MigrationToolOption[] = [
  {
    id: 'selenium-playwright',
    label: 'Selenium → Playwright',
    sourceLabel: 'Selenium (WebDriver)',
    targetLabel: 'Playwright TypeScript',
    description: 'Migrate Selenium WebDriver tests (Java, Python, C#) to Playwright TypeScript with page objects and fixtures.',
    sourceLanguages: ['Java', 'Python', 'C#', 'JavaScript'],
    icon: '🔄',
    supportsStrategies: true,
  },
  {
    id: 'selenium-api-playwright',
    label: 'Selenium + REST Assured → Playwright',
    sourceLabel: 'Selenium + REST Assured (Java)',
    targetLabel: 'Playwright TypeScript (UI + API)',
    description: 'Migrate dual-layer Selenium UI + REST Assured API frameworks to a unified Playwright TypeScript solution.',
    sourceLanguages: ['Java'],
    icon: '🔗',
    supportsStrategies: true,
  },
  {
    id: 'robot-playwright',
    label: 'Robot Framework → Playwright',
    sourceLabel: 'Robot Framework',
    targetLabel: 'Playwright TypeScript',
    description: 'Convert Robot Framework keyword-driven tests and resource files to Playwright TypeScript page objects and specs.',
    sourceLanguages: ['Robot/Python'],
    icon: '🤖',
    supportsStrategies: true,
  },
  {
    id: 'uft-playwright',
    label: 'UFT/QTP → Playwright',
    sourceLabel: 'UFT / QTP (VBScript)',
    targetLabel: 'Playwright TypeScript',
    description: 'Migrate HP UFT (formerly QTP) VBScript-based tests to modern Playwright TypeScript with equivalent assertions.',
    sourceLanguages: ['VBScript'],
    icon: '⚙️',
    supportsStrategies: true,
  },
  {
    id: 'cypress-playwright',
    label: 'Cypress → Playwright',
    sourceLabel: 'Cypress',
    targetLabel: 'Playwright TypeScript',
    description: 'Convert Cypress test suites to Playwright — mapping commands, fixtures, intercepts, and network mocking.',
    sourceLanguages: ['JavaScript', 'TypeScript'],
    icon: '🌲',
    supportsStrategies: true,
  },
];
