const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const { spawn } = require('child_process');

const app = express();
app.use(cors());
app.use(express.json());

// ─── State ────────────────────────────────────────────────────────
let migrationProcess = null;
let sseClients = [];
let migrationStatus = 'idle'; // idle | running | completed | failed

// ─── Helpers ──────────────────────────────────────────────────────
function broadcast(event, data) {
  const payload = `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`;
  sseClients.forEach((res) => res.write(payload));
  if (event === 'done' || event === 'error_event') {
    sseClients.forEach((res) => res.end());
    sseClients = [];
  }
}

function logEntry(level, message) {
  return { timestamp: new Date().toLocaleTimeString(), level, message };
}

function emit(level, message) {
  broadcast('log', logEntry(level, message));
}

// Maps (tool, strategy) → { agentFolder, promptFile }
// agentFolder is relative to __dirname/.. (workspace root)
const AGENT_CONFIG = {
  'selenium-playwright': {
    'reverse-engineering': { agentFolder: 'migration-agent',        promptFile: 'selenium-re-migration.agent.md' },
    'direct':              { agentFolder: 'direct-migration-agent', promptFile: 'selenium-direct-migration.agent.md' },
  },
  'selenium-api-playwright': {
    'reverse-engineering': { agentFolder: 'migration-agent',        promptFile: 'selenium-re-migration.agent.md' },
    'direct':              { agentFolder: 'direct-migration-agent', promptFile: 'selenium-direct-migration.agent.md' },
  },
  'cypress-playwright': {
    'reverse-engineering': { agentFolder: 'migration-agent',        promptFile: 'cypress-conversion-orchestrator.agent.md' },
    'direct':              { agentFolder: 'direct-migration-agent', promptFile: 'cypress-direct-migration.agent.md' },
  },
  'robot-playwright': {
    'reverse-engineering': { agentFolder: 'migration-agent',        promptFile: 'robot-conversion-orchestrator.agent.md' },
    'direct':              { agentFolder: 'direct-migration-agent', promptFile: 'robot-direct-migration.agent.md' },
  },
  'uft-playwright': {
    'reverse-engineering': { agentFolder: 'migration-agent',        promptFile: 'uft-conversion-orchestrator.agent.md' },
    'direct':              { agentFolder: 'direct-migration-agent', promptFile: 'uft-direct-migration.agent.md' },
  },
};

function resolveAgent(tool, strategy) {
  const toolConfig = AGENT_CONFIG[tool];
  if (!toolConfig) return { agentFolder: 'migration-agent', promptFile: 'selenium-re-migration.agent.md' };
  // fall back to reverse-engineering if the requested strategy has no entry
  return toolConfig[strategy] || toolConfig['reverse-engineering'] || Object.values(toolConfig)[0];
}

// ─── Routes ───────────────────────────────────────────────────────

// SSE stream endpoint — browser connects first, then POST /migrate
app.get('/api/migrate/stream', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();
  sseClients.push(res);
  req.on('close', () => {
    sseClients = sseClients.filter((c) => c !== res);
  });
});

app.post('/api/migrate', (req, res) => {
  if (migrationStatus === 'running') {
    return res.status(409).json({ error: 'A migration is already running.' });
  }

  const config = req.body;
  const { tool, strategy = 'reverse-engineering', sourcePath, outputPath, projectName, sourceLanguage, webTarget, apiTarget } = config;

  // Validate paths
  if (!fs.existsSync(sourcePath)) {
    return res.status(400).json({ error: `Source path does not exist: ${sourcePath}` });
  }

  // Resolve agent folder + prompt file based on tool × strategy
  const { agentFolder, promptFile: agentPromptFile } = resolveAgent(tool, strategy);
  const agentRoot = path.resolve(__dirname, '..', agentFolder);

  if (!fs.existsSync(agentRoot)) {
    return res.status(500).json({ error: `Agent folder not found: ${agentRoot}` });
  }

  // Build project config written to migration-source.json / selenium-source.json
  const projectConfig = {
    path: sourcePath,
    type: sourceLanguage,
    language: sourceLanguage,
    migrationStrategy: strategy,
    outputFolder: path.basename(outputPath),
    features: [],
    notes: `Auto-generated by Migration UI. Tool: ${tool}, Strategy: ${strategy}`,
  };

  if (typeof webTarget === 'string' && webTarget.trim()) projectConfig.webTarget = webTarget.trim();
  if (typeof apiTarget === 'string' && apiTarget.trim()) projectConfig.apiTarget = apiTarget.trim();

  const sourceConfig = {
    seleniumSourceRoot: sourcePath,
    migrationOutputPath: outputPath,
    activeProject: projectName,
    migrationTool: tool,
    migrationStrategy: strategy,
    projects: { [projectName]: projectConfig },
  };

  const configPath = path.join(agentRoot, 'migration-source.json');
  const seleniumCompatConfigPath = path.join(agentRoot, 'selenium-source.json');
  const serializedConfig = JSON.stringify(sourceConfig, null, 2);
  fs.writeFileSync(configPath, serializedConfig);
  fs.writeFileSync(seleniumCompatConfigPath, serializedConfig);

  const agentPromptPath = path.join(agentRoot, '.github', 'prompts', agentPromptFile);

  migrationStatus = 'running';
  res.json({ message: 'Migration started', configPath, seleniumCompatConfigPath, agentPromptPath, strategy, agentFolder });

  // Stream progress asynchronously
  setImmediate(() => runMigration(agentRoot, agentPromptFile, agentPromptPath, configPath, seleniumCompatConfigPath, sourceConfig, strategy));
});

function runMigration(agentRoot, agentPromptFile, agentPromptPath, configPath, seleniumCompatConfigPath, sourceConfig, strategy) {
  const strategyLabel = strategy === 'direct'
    ? '⚡ Direct Migration (Selenium → Playwright)'
    : '🔍 Reverse Engineering (Selenium → User Stories → Playwright)';

  emit('info', `STAGE: Initialising ${strategyLabel}`);
  emit('info', `📂 Source project:    ${sourceConfig.seleniumSourceRoot}`);
  emit('info', `📁 Output path:       ${sourceConfig.migrationOutputPath}`);
  emit('info', `🔧 Tool:              ${sourceConfig.migrationTool}`);
  emit('info', `🗺️  Strategy:          ${strategyLabel}`);
  emit('info', `📋 Agent prompt:      ${agentPromptFile}`);
  emit('info', `🏠 Agent root:        ${path.basename(agentRoot)}`);
  emit('info', '');
  emit('info', '─────────────────────────────────────────────────');
  if (strategy === 'direct') {
    emit('info', '  Pipeline: PRE-FLIGHT → TRANSLATE → RUN → EVIDENCE → GATE 1');
    emit('info', '  No analysis docs. No user stories. Fastest path.');
  } else {
    emit('info', '  Pipeline: PRE-FLIGHT → STAGE 1 (analyze) → STAGE 2 (stories)');
    emit('info', '            → GATE 1 (business review) → STAGE 3 (implement)');
    emit('info', '            → RUN → EVIDENCE → GATE 2');
  }
  emit('info', '─────────────────────────────────────────────────');
  emit('info', `  Config written: ${path.basename(configPath)}`);
  emit('info', '  Launching Copilot agent from UI...');
  emit('info', '─────────────────────────────────────────────────');
  emit('info', '');

  const vscodePath = process.env.VSCODE_BIN || 'code';
  const orchestrationPrompt = `Use #file:.github/prompts/${agentPromptFile} and #file:migration-source.json. Run the migration end to end now.`;
  const chatArgs = [
    'chat',
    '--mode',
    'agent',
    '--reuse-window',
    '--add-file',
    agentPromptPath,
    '--add-file',
    configPath,
    '--add-file',
    seleniumCompatConfigPath,
    orchestrationPrompt,
  ];

  emit('info', `Executing: ${vscodePath} ${chatArgs.join(' ')}`);
  migrationProcess = spawn(vscodePath, chatArgs, {
    cwd: agentRoot,
    shell: true,
    windowsHide: true,
  });

  migrationProcess.stdout.on('data', (chunk) => {
    const text = chunk.toString().trim();
    if (text) {
      emit('info', text);
    }
  });

  migrationProcess.stderr.on('data', (chunk) => {
    const text = chunk.toString().trim();
    if (text) {
      emit('warn', text);
    }
  });

  migrationProcess.on('error', (err) => {
    migrationStatus = 'failed';
    emit('error', `Failed to launch VS Code chat: ${err.message}`);
    broadcast('error_event', { message: err.message });
    migrationProcess = null;
  });

  migrationProcess.on('close', (code) => {
    if (code === 0) {
      migrationStatus = 'completed';
      emit('success', '✅ Copilot agent command launched successfully from UI.');
      emit('success', 'Migration execution is now running in your VS Code chat session.');
      broadcast('done', { message: 'Agent launched successfully' });
    } else {
      migrationStatus = 'failed';
      emit('error', `Agent launch exited with code ${code}.`);
      broadcast('error_event', { message: `Agent launch failed with code ${code}` });
    }
    migrationProcess = null;
  });

  emit('info', '─────────────────────────────────────────────────');
  emit('info', 'Configuration summary:');
  emit('info', JSON.stringify(sourceConfig, null, 2));
}

app.post('/api/migrate/stop', (req, res) => {
  if (migrationProcess) {
    try { migrationProcess.kill('SIGTERM'); } catch {}
    migrationProcess = null;
  }
  migrationStatus = 'idle';
  res.json({ message: 'Stopped' });
});

app.get('/api/migrate/status', (req, res) => {
  res.json({ status: migrationStatus });
});

// ─── Start ────────────────────────────────────────────────────────
const PORT = 3001;
app.listen(PORT, () => {
  console.log(`Migration backend running on http://localhost:${PORT}`);
});
